<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_Quickview
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<?php
/**
 * @var \Dss\Quickview\Block\Product\Social $block
 */
?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->getConfigShowEmail()): ?>
    <?php $blockObj = $block->getLayout()->createBlock(\Dss\Quickview\Block\Product\EmailToFriend::class); ?>
    <?php $emailUrl = $blockObj->getEmailToFriendUrl($_product); ?>
    <a href="<?= $escaper->escapeUrl($emailUrl) ?>"
        class="action mailto friend"><span><?= $escaper->escapeHtml(__('Email')) ?></span></a>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {"Dss_Quickview/js/wishlist":{}}
    }
</script>