<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_Quickview
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>
<?php
/**
 * @var \Dss\Quickview\Block\Initialize $block
 */
?>
<?php $product = $block->getProduct(); ?>
<?php
    $helper = $block->getHelper();
    $removeReview = $helper->getRemoveReview();
    $removeMoreInfo = $helper->getRemoveMoreInfo();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Dss_Quickview/js/dss_beforebodyend": {
                "removeReview": "<?= /* @noEscape */ $removeReview; ?>",
                "removeMoreInfo": "<?= /* @noEscape */ $removeMoreInfo; ?>"
            }
        }
    }
</script>
